name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: subosito/flutter-action@v2
      - name: build web
        run: |
          flutter pub get
          flutter test
          flutter build web --release
      - name: deploy
        working-directory: ./build/web
        run: |
          git config user.name deopoler
          git config user.email seonjin6804@gmail.com
          git add .
          git commit -m "build: build web"
          git push
      
